#
# Makefile for nfc devices
#

obj-$(CONFIG_NFC_PN544)		+= pn544/
obj-$(CONFIG_NFC_MICROREAD)	+= microread/
obj-$(CONFIG_NFC_PN533)		+= pn533.o
obj-$(CONFIG_NFC_WILINK)	+= nfcwilink.o
obj-$(CONFIG_NFC_MEI_PHY)	+= mei_phy.o
obj-$(CONFIG_NFC_QNCI)		+= nfc-nci.o
obj-$(CONFIG_NFC_PN548)	+= pn548.o pn548_hwadapter.o
obj-$(CONFIG_NFC_PN547)		+= pn547.o
obj-$(CONFIG_LGE_NFC_PN547_C2)	+= pn547_lge_hwadapter.o 
obj-$(CONFIG_LGE_NFC_PN547_C2)	+= pn547_lge.o




ccflags-$(CONFIG_NFC_DEBUG) := -DDEBUG
